apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: podmonitor-ns
spec: {}
status: {}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: podmon-sa
  namespace: podmonitor-ns

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podmon-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - kk.dev
  resources:
  - podmonitors
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podmon-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: podmon-sa
  namespace: podmonitor-ns
roleRef:
  kind: ClusterRole
  name: podmon-cluster-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: podmonitor-controller
  name: podmonitor-controller
  namespace: podmonitor-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podmonitor-controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: podmonitor-controller
    spec:
      serviceAccountName: podmon-sa
      containers:
      - image: #REGISTRY#/abhisheksuran/podmonitor:#TAG_NAME#
        name: podmonitor
        env:
        - name: RUST_LOG
          value: "info"
        resources: {}
status: {}
