on:
  push:
    tags:
      - '*'

env:
  REGISTRY: 'docker.io'
  project_name: 'podmonitor'

jobs:
  checkout_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: action/checkout@v4
      - run: |
          sed -i -e "s/#REGISTRY#/$REGISTRY/g" ./*.yaml
          sed -i -e "s/#TAG_NAME#/${GITHUB_REF_NAME}/g" ./*.yaml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: abhisheksuran/podmonitor:${GITHUB_REF_NAME}

      - name: Asset name as per tag
        run: mv PodMonitor.yaml PodMonitor_${GITHUB_REF_NAME}.yaml

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            PodMonitor_${GITHUB_REF_NAME}.yaml