on:
  push:
    tags:
      - '*'

env:
  REGISTRY: 'docker.io'
  project_name: 'podmonitor'

jobs:
  checkout_build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update YAML files
        run: |
          sed -i -e "s/#REGISTRY#/$REGISTRY/g" ./*.yaml
          sed -i -e "s/#TAG_NAME#/${{ github.ref_name }}/g" ./*.yaml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.REGISTRY }}/abhisheksuran/podmonitor:${{ github.ref_name }}

      - name: Rename asset
        run: mv PodMonitor.yaml PodMonitor_${{ github.ref_name }}.yaml

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            PodMonitor_${{ github.ref_name }}.yaml
